# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Helper": "client.ipynb",
         "Client": "client.ipynb",
         "getCardToken": "client.ipynb",
         "chargeCard": "client.ipynb",
         "verifyOtp": "client.ipynb",
         "qrPayment": "client.ipynb",
         "checkStatus": "client.ipynb",
         "PaymentStatusError": "client.ipynb",
         "paymentStatus": "client.ipynb",
         "wechatPay": "client.ipynb",
         "alipay": "client.ipynb",
         "GBPrimePayException": "exceptions.ipynb",
         "GBPResponseError": "exceptions.ipynb",
         "Keys": "helper.ipynb",
         "checkSum": "helper.ipynb"}

modules = ["client.py",
           "exceptions.py",
           "helper.py"]

doc_url = "https://thanakijwanavit.github.io/globalPrimePay/"

git_url = "https://github.com/thanakijwanavit/globalPrimePay"

def custom_doc_links(name): return None
